name: BUILD
on:
  push:
    branches: [dev, main]
  pull_request:
     types: [opened, synchronized, reopened]

jobs:
  Build:
    name: Build App
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        
      - name: Install dependencies
        run: |
          npm install

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: node_modules/bin/**

      # - name: Run tests with coverage
      #   run: |
      #     npm test -- --coverage

      # - name: SonarQube Scan
      #   uses: sonarsource/sonarqube-scan-action@v6
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #     SONAR_HOST_URL: https://sonarcloud.io
          
          
     
