name: Node.js CI with SonarQube and Auto PR

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-test-sonar:
    runs-on: ubuntu-latest
    container:
      image: node:18

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Install npm dependencies
        run: |
          npm install

      - name: Fix Jest permissions
        run: chmod +x node_modules/.bin/jest

      - name: Run tests with coverage
        run: |
          npm test -- --coverage

      - name: SonrQube Scan
        uses: sonarsource/sonarcloud-github-action@v5.0.0
        with:
          args: >
            -Dsonar.projectkey=RathanMC_deploy3
            -Dsonar.organization=rathanmc
            -Dsonar.projectName="Deploy3"
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN}}
          SONAR_HOST_URL: https://sonarcloud.io
          
      - name: Chech Quality Gate
        uses: SonarSource/sonarqube-quality-gate-action@v1.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN}}
            
          
          
     
