name: Node.js CI with SonarQube and Auto PR

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-test-sonar:
    runs-on: ubuntu-latest
    container:
      image: node:18

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Install npm dependencies
        run: |
          npm install

      - name: Fix Jest permissions
        run: chmod +x node_modules/.bin/jest

      - name: Run tests
        run: |
          npm test

      - name: SonrQube Scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
          projectKey: my-node-project
          organization: DevSecOps
          projectName: My Node Project
        env:
          SOONAR_TOKEN: ${{ secrets.Sonar_Token}}

